---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels: ["dependencies", "github-actions"]
    commit-message:
      prefix: "ci"
      include: scope

  - package-ecosystem: terraform
    directory: /modules/vpc
    schedule:
      interval: weekly
    labels: ["dependencies", "terraform"]
  - package-ecosystem: terraform
    directory: /modules/eks
    schedule:
      interval: weekly
    labels: ["dependencies", "terraform"]
  - package-ecosystem: terraform
    directory: /modules/rds
    schedule:
      interval: weekly
    labels: ["dependencies", "terraform"]
  - package-ecosystem: terraform
    directory: /modules/iam-roles
    schedule:
      interval: weekly
    labels: ["dependencies", "terraform"]
  - package-ecosystem: terraform
    directory: /modules/s3-secure
    schedule:
      interval: weekly
    labels: ["dependencies", "terraform"]
  - package-ecosystem: terraform
    directory: /modules/kms
    schedule:
      interval: weekly
    labels: ["dependencies", "terraform"]
  - package-ecosystem: terraform
    directory: /modules/state-backend
    schedule:
      interval: weekly
    labels: ["dependencies", "terraform"]
